### ISSUE TITLE
Cara penggunan

### ISSUE THREAD

**Issue by robaitusman** [rzlnhd/WhatsApp-Blast#4]
Halo om
Salam kenal
 Boleh tau cara penggunaannya kah?

**Comment by rzlnhd** [comment]
> Halo om
> Salam kenal
> Boleh tau cara penggunaannya kah?

Silahkan cek Ebook [Panduan Penggunaan](https://bit.ly/WABlastV3), atau bisa cek playlist [Video Tutorialnya](https://bit.ly/WABlastVidV3). Terimaksih

**Comment by robaitusman** [comment]
oke maasih om
